---

# Create CentOS

    - name: "----->Create a network interface for VM"
      azure_rm_networkinterface:
        name: "{{nic_root_name}}"
        resource_group: "{{resourcegroup_name}}"
        virtual_network: "{{virtualnetwork_name}}"
        subnet_name: "{{subnet_name}}"
        security_group: "{{securitygroup_name}}"
        public_ip_address_name: "{{public_ip_name}}"
#        ip_configurations:
#          - name: "ipconfig"
#            public_ip_address_name: "{{public_ip_name}}"
#            primary: True
#      with_sequence: count="{{instances_number}}"

    - name: "----->Create VM with existing NIC"
      azure_rm_virtualmachine:
        resource_group: "{{resourcegroup_name}}"
        name: "{{vm_root_name}}"
        vm_size: "{{vm_size}}"
        managed_disk_type: "{{disk_type}}"
        admin_username: "{{admin_username}}"
#        admin_password: xxxxxxx
#        availability_set: "{{availabilityset_name}}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{admin_username}}/.ssh/authorized_keys"
            key_data: "{{lookup('file', '{{admin_pub_path}}') }}"
        network_interface_names: "{{nic_root_name}}"
#        custom_data: "{{ lookup('file', 'cloud-init.yml') }}"
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.5'
          version: latest
#      with_sequence: count="{{instances_number}}"