---

- block: # Ubuntu server
    - name: Ubuntu - Installing NGINX the latest version
      apt: name=nginx state=latest
    
    - name: Ubuntu - Start NGINX
      service: name=nginx state=started enabled=yes  
   
    - name: Ubuntu - Copy the NGINX config file and restart nginx
      copy: src=/tmp/config/app_site.cfg dest=/etc/nginx/sites-available/app_site.cfg
      notify: restart_nginx
        
    - name: Ubuntu - Create symlink for NGINX
      file: src=/etc/nginx/sites-available/app_site.cfg dest=/etc/nginx/sites-enabled/default state=link
      notify: restart_nginx
  when: ansible_os_family == "Debian"

- block: # CentOS server
    - name: CentOS - copy the NGINX nginx.repo file
      copy: src=/tmp/config/nginx.repo dest=/etc/yum.repos.d/nginx.repo
    
    - name: CentOS - Installing NGINX the latest version
      yum: name=nginx state=latest
    
    - name: CentOS - Start NGINX
      service: name=nginx state=started enabled=yes
    
    - name: CentOS - Copy the NGINX config file and restart nginx
      copy: src=/tmp/config/app_site.cfg dest=/etc/nginx/conf.d/default.conf
      notify: restart_nginx
      
  when: ansible_os_family == "RedHat"


- name: Ubuntu_CentOS - Copy application files to server
  copy: src={{ source_file }} dest={{ destin_file }} mode=0555
  notify: restart_nginx

- name: Ubuntu_CentOS - Generate html files
  template: src={{ source_file }}/about.j2 dest={{ destin_file }}/about.html mode=0555
  notify: restart_nginx

- name: Ubuntu_CentOS - Copy the NGINX config file and restart nginx
  copy: src=/tmp/config/.htpasswd dest=/etc/nginx/.htpasswd
  notify: restart_nginx
