---
- name: Show info from server
  hosts: all
  become: yes

  tasks:
   - shell: uptime
       register: result 
   - debug:
       msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }} | kernel: {{ ansible_kernel }} | IP: {{ ansible_all_ipv4_addresses }} | uptime: {{ result }}"
