---
- name: Install NGINX
  hosts: server_web
  become: yes
  
  tasks:
  - name: Installing nginx the latest version
    apt: name=nginx state=latest
  - name: start nginx
    service: name=nginx state=started enabled=yes