---
  admin_username: alex
  os_type: "centos"
  project_prefix: "laba-8"
  location: "westeurope"
  vm_size: "Standard_B1s"
  disk_type: "Standard_LRS"
  virtualnetwork_cidr: "172.16.0.0/16"
  subnet_cidr: "172.16.1.0/24"
  admin_pub_path: "/key/laba08.pub"
  resourcegroup_name: "{{project_prefix}}-rg"
#  availabilityset_name: "{{project_prefix}}-avset"
  virtualnetwork_name: "{{project_prefix}}-vnet"
  subnet_name: "{{project_prefix}}-subnet"
  securitygroup_name: "{{project_prefix}}-nsg"
  vm_root_name: "{{project_prefix}}-vm-{{os_type}}"
  public_ip_name: "{{project_prefix}}-ip-{{os_type}}"
  nic_root_name: "{{project_prefix}}-nic-{{os_type}}"