---
  admin_username: alex
  var: "linux"
  project_prefix: "test_laba_8"
  location: "westeurope"
  vm_size: "Standard_B1s"
  disk_type: "Standard_LRS"
  virtualnetwork_cidr: "172.16.0.0/16"
  subnet_cidr: "172.16.1.0/24"
  admin_pub_path: "/key/laba08.pub"
  resourcegroup_name: "{{project_prefix}}_rg"
  availabilityset_name: "{{project_prefix}}_avset"
  virtualnetwork_name: "{{project_prefix}}_vnet"
  subnet_name: "{{project_prefix}}_subnet"
  securitygroup_name: "{{project_prefix}}_nsg"
  vm_root_name: "{{project_prefix}}_vm"
  public_ip_name: "{{project_prefix}}_ip"
  nic_root_name: "{{project_prefix}}_nic"